### ISSUE TITLE
Running cmake in the build folder cannnot find rnbo_source.cpp 

### ISSUE THREAD

**Issue by semsion** [Cycling74/rnbo.example.juce#15]
Thank you for the interesting integration here!

OS: Windows 10
RNBO: 1.1.1
Max: 8.5.4

The issue:

When runing `cmake .. -G "Visual Studio 16"` in the build folder, an error is being returned in the command prompt of `Cannot find source file: rnbo_source.cpp`, dispite this file not being present in the C++ source code export from Max.

**Comment by semsion** [comment]
Have got a little further, however this also hasn't been tested if fully working in Unity yet, but inside of /CMakeLists.txt - changed the “rnbo_source.cpp” string to the name of the main exported C++ file, EG: `set(RNBO_CLASS_FILE_NAME "plugin.cpp" ... )`,  which got rid of the error, and allowed the build to complete.

**Comment by semsion** [comment]
Have got a little further, however this also hasn't been tested if fully working in Unity yet, but inside of /CMakeLists.txt - changed the “rnbo_source.cpp” string to the name of the main exported C++ file, EG: set(RNBO_CLASS_FILE_NAME "plugin.cpp" ... ), which got rid of the error, and allowed the build system to complete.

There were many warnings when doing the actual build in the next step, but no errors.

**Comment by x37v** [comment]
@semsion you can set cmake cache variables on the commandline like:
```
cmake -DRNBO_CLASS_FILE_NAME=plugin.cpp ..
```

FYI, if you're trying to target unity, you might wanna checkout our new native plugin implementation: https://github.com/Cycling74/rnbo.unity.audioplugin/

**Comment by semsion** [comment]
Wow, that new native plugin looks well featured :)

Excellent stuff!
