### ISSUE TITLE
How to build a custom UI plugin for Windows

### ISSUE THREAD

**Issue by mjcella** [Cycling74/rnbo.example.juce#16]
I have successfully built a custom UI plugin (VST3 and AU formats) with a custom UI, following the `README.md` and `CUSTOM_UI.md` tutorials. My plugin is called "bloom".

Here's how I build (I'm on MacOS):

```
cd build
cmake -G Ninja ..
cmake --build .
```

Then when I go to `build/RNBOAudioPlugin_artefacts/Debug/VST3`, and I select to view the package contents of the bloom.vst3 file, here's what I see:

```
Contents
    - Info.plist
    - MacOS
        - bloom (Unix executable)
    - PkgInfo
```

Is there a way to also generate an executable that can run on Windows machines?

I've looked through the tutorials, Plugin.cmake, and other files in this repo, but I can't find any information on it. Thanks!

**Comment by x37v** [comment]
@mjcella you're wanting to cross-compile on the mac to build a windows executable?
looking into `mingw`

**Comment by mjcella** [comment]
Yep that's right. Thanks, I'll check that out!
