### ISSUE TITLE
Custom UI plugin parameters all set to 0 after closing & reopening plugin window

### ISSUE THREAD

**Issue by mjcella** [Cycling74/rnbo.example.juce#6]
I'm using Ableton Live 10 as my DAW on MacOS.

If I close the plugin window of my custom UI VST and then reopen it, all the parameters reset to 0 (the lowest setting in the slider) no matter what value I had perviously set them to. I've tested this for both the VST and AU versions.

In the tutorial I followed (https://rnbo.cycling74.com/learn/programming-a-custom-ui-with-juce), it mentioned returning to the updateAllParams() function, but we never return to it. Wondering if maybe that could be the issue, or if there's some other small place in the code that might need a tweak to handle this edge case.

**Comment by starakaj** [comment]
Should be fixed for the next release, when we merge `develop` back into `main` with the next RNBO release.

**Comment by mjcella** [comment]
Awesome, excited to test it out - thanks so much for your help on this!

**Comment by mjcella** [comment]
I just rebuilt my plugin with a custom UI after updating to RNB0 1.1.0 and following the new tutorial, and the issue is fixed. Thank you so much!
