### ISSUE TITLE
Custom UI VST crashes when changing a parameter if effect is bypassed

### ISSUE THREAD

**Issue by mjcella** [Cycling74/rnbo.example.juce#7]
I'm running Ableton Live 10 on MacOs.

If I bypass my VST and then change a parameter inside the Live device containing the VST, Live crashes. (Changing the parameter directly in the VST plugin window works fine while bypassed).

Wondering again if there might be another small change needed to cover this edge case? Otherwise the VST is working perfectly 😃

**Comment by starakaj** [comment]
Okay, this one should be fixed for the next release, when we merge develop back into main with the next RNBO release. Thanks for filing these!

**Comment by mjcella** [comment]
This one is also fixed after moving to RNB0 1.1.0 and re-building following the new tutorial. Thank you so much again!
