### ISSUE TITLE
Buggy sound on FL STUDIO

### ISSUE THREAD

**Issue by pedrononino** [Cycling74/rnbo.example.juce#8]
Hello! I've build 2 different plugins using this and C++ export, one of them is an EQ and the other is an Oscilator. Both of them sounded really strange/choppy/distorted/glitchy on FL Studio so I've started wondering if this is some issue related to RNBO and FL Studio specifically because it worked ok on REAPER and inside Max vst~

**Comment by x37v** [comment]
hey @pedrononino we're looking into this

**Comment by x37v** [comment]
resolved with RNBO `1.1` (just released), you'll want to use the latest `main` of this template as well
